#!/bin/sh
# 
# A git SupyBot post-receive hook written by KittyKatt.
#
# Content copyright KittyKatt (Brett Bohnenkamper: kittykatt@archlinux.us)
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#

# Change project to the name of your project as in <project>.git
project="projectname"

# Change repopath to the path to your gitosis repository
repopath="/srv/git/repositories"

# Set this to the URL of your gitweb repository's main page
yoururl="http://git.example.com/"

# Set the host and port number that SupyBot's Listener plugin is listening on
_host="localhost"
_port="8082"
_mytcp="/dev/tcp/$_host/$_port"


#
# Bro, don't touch these lines following this one.
#

cd $repopath/$project.git

merged=$(git rev-parse HEAD)
refname=$(cat ./hooks/refname.txt 2>/dev/null)
refname=${refname##refs/heads/}
gitver=$(git --version)
gitver=${gitver##* }
rev=$(git describe ${merged} 2>/dev/null)

# project=$(pwd | awk -F"/" '{print $NF}')
commit=$(git log -1 --format=format:"%h" $refname)
author=$(git log -1 --format=format:"%cn" $refname)

changes=$(git log -1 --shortstat $refname | grep "files changed" | sed -e 's/files changed/file(s) changed/' -e 's/insertions(+)/(+)/' -e 's/deletions(-)/(-)/' -e 's/^ //')

message=$(git log -1 --format=format:"%s" $refname)


# Short URL's at sCURL.tk - These have a spam timer on them so keep at least 10 seconds between submissions. gitweb version 
# cgit version
url=$(curl -sL "http://scurl.tk/api.php?format=simple&action=shorturl&url=${yoururl}?p=${project}.git;a=commit;h=${commit}" \ | sed -n 's/.*\(http:\/\/tinyurl.com\/[a-z0-9][a-z0-9]*\).*/\1/p' | uniq; echo -n "")

if [ -z "$message" ]; then
  message="No message supplied for commit."
  exit 0
fi
if [ -z "$changes" ]; then
  changes="No obvious changes made."
fi

function snd2irc() {
        # $1 command
        exec 5<> $_mytcp 2>/dev/null
        [[ $? -gt 0 ]] && return 1
        printf "$1" >&5
        exec 5>&-
        return 0
}

snd2irc "`echo -e "\x02${project}:\x02 \x037${refname} \x033${author}\x0f * \x02${commit}\x0f / (${changes}): \x02${message}\x02 - ${url}"`"
